name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    #credentials to connect to AWS
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Runs a set of commands using the runners shell; THIS DOESN'T WORK
    - name: Run a multi-line script
      run: |
         python -m pip install --upgrade pip
         pip3 install -r requirements.txt -t .
         zip -r dep-master.zip .
         export PATH=$PATH:$(pwd)

    #Deploy main.py to AWS
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@v0.0.4
      with:
            function_name: ${{ secrets.AWS_FUNCTION_NAME }}
            zip_file: dep-master.zip